# Dockerfile to build Linux kernel
FROM ubuntu
MAINTAINER Vijo Cherian codervijo@gmail.com

#RUN apt install -y vim
#RUN apt install -y git net-tools ssh
#RUN apt install -y ncurses-devel make gcc bc openssl-devel

COPY linux-stable /usr/src/linux

