FROM ubuntu:22.04
RUN apt-get update && \
	apt-get install -y build-essential
RUN apt-get install -y qemu binfmt-support qemu-user-static
# /usr/local/share/kivy-examples/demo/pictures
#CMD ["/usr/bin/xeyes"]
