FROM ubuntu:18.04
MAINTAINER Vijo Cherian codervijo@gmail.com

RUN apt-get update

# Install some dependencies
RUN 	apt-get install -y vim git net-tools

# Install mongodb
RUN 	apt-get install -y mongodb


