help:
	@echo "\tmongoose : clone mongoose source"
	@echo "\trun      : Run webui login example"

mongoose:
	git clone https://github.com/cesanta/mongoose.git

run: mongoose
	cd mongoose/examples/webui-login && make